LITReview/LITReview/urls.py
from django.contrib import admin
from django.urls import include, path
from authentication import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("book_review/", include("book_review.urls")),
    path("", auth_views.insc_connect, name="connection"),
    path("inscription/", auth_views.inscription, name="inscription"),
    path("logout", auth_views.logout_view, name="logout")
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LITReview/book_review/urls.py
from django.urls import path, re_path
from . import views

app_name = "book_review"
urlpatterns = [
    path("", views.flux, name="flux"),
    path("posts", views.posts, name="posts"),
    path("abonnements", views.abonnements, name="abonnements"),
    re_path(r"^crea_ticket(?:/(?P<ticket_id>[0-9]+)/)?$",
            views.crea_ticket,
            name="crea_ticket"),
    path("crea_review", views.crea_review, name="crea_review"),
    path("reply_ticket/<ticket_id>", views.reply_ticket, name="reply_ticket"),
    
]

LITReview/templates/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    {% load static %}
    <link rel="icon" type="image/png" href="{% static 'book_review/Images/favicon.png' %}" />  
    <link rel="stylesheet" type="text/css" href="{% static 'book_review/css/styles.css' %}">
    {% if sup_nav %}
    <link rel="stylesheet" type="text/css" href="{% static 'book_review/css/styles_ss_nav.css' %}">
    {% endif %}
    <title>LITReview</title>
</head>
<body>
    <header class="bg-dark">
        <div class="container-fluid">
            <nav class="row navbar navbar-expand-md navbar-dark">
                <a class="col col-md-6 col-lg-2 {% if not sup_nav %} offset-lg-5 {% endif %} navbar-brand text-center" {% if not sup_nav %} href="{% url 'book_review:flux' %}" {% endif %}>
                    <img class="logo" src="{% static 'book_review/Images/logo_LIT.png' %}" height="40" alt="logo du site">
                    LITReview
                </a>
                <button class="col-auto navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div id="navbarNav" class="collapse navbar-collapse col col-md-6 col-lg-5">
                    <ul class=" navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'book_review:flux' %}">Flux</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'book_review:posts' %}">Posts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'book_review:abonnements' %}">Abonnements</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">Se déconnecter</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>
    <div class="contenu">
            {% block content %} {% endblock %}
    </div>
    <footer>
                <p class="text-footer">Made by Planat Loïc</p>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
</body>
</html>