LITReview/LITReview/urls.py
from django.contrib import admin
from django.urls import include, path
from authentication import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("book_review/", include("book_review.urls")),
    path("", auth_views.insc_connect, name="connection"),
    path("inscription/", auth_views.inscription, name="inscription"),
    path("logout", auth_views.logout_view, name="logout")
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LITReview/book_review/urls.py
from django.urls import path, re_path
from . import views

app_name = "book_review"
urlpatterns = [
    path("", views.flux, name="flux"),
    path("posts", views.posts, name="posts"),
    path("abonnements", views.abonnements, name="abonnements"),
    re_path(r"^crea_ticket(?:/(?P<ticket_id>[0-9]+)/)?$",
            views.crea_ticket,
            name="crea_ticket"),
    path("crea_review", views.crea_review, name="crea_review"),
    path("reply_ticket/<ticket_id>", views.reply_ticket, name="reply_ticket"),
    
]

LITReview/book_review/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings
from django.db import models
from PIL import Image


class Ticket(models.Model):
    IMAGE_MAX_SIZE = (300, 300)
    title = models.CharField(max_length=128)
    description = models.CharField(max_length=2048, blank=True)
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE)
    image = models.ImageField(upload_to="images/", blank=True)
    time_created = models.DateTimeField(auto_now_add=True)

    def resize_image(self):
        image = Image.open(self.image)
        image.thumbnail(self.IMAGE_MAX_SIZE)
        image.save(self.image.path)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.image:
            self.resize_image()

    def __str__(self):
        return f"Ticket {self.title} par {self.user}"
    

class Review(models.Model):
    ticket = models.ForeignKey(to=Ticket, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(
        # validates that rating must be between 0 and 5
        validators=[MinValueValidator(0), MaxValueValidator(5)])
    headline = models.CharField(max_length=128)
    body = models.CharField(max_length=8192, blank=True)
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    time_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Critique"
        verbose_name_plural = "Critiques"

    def __str__(self):
        return f"Critique du ticket {self.ticket.title} par {self.user}"


class UserFollows(models.Model):
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="following")
    followed_user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="followed_by")

    class Meta:
        # ensures we don't get multiple UserFollows instances
        # for unique user-user_followed pairs
        unique_together = ('user', 'followed_user', )
        verbose_name = "Abonnement: abonné/suivi"
        verbose_name_plural = "Abonnements: abonné/suivi"
    
    def __str__(self):
        return f"{self.user} / {self.followed_user}"

LITReview/book_review/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user
from .models import Ticket, Review, UserFollows
from PIL import Image
import os


STARS = [1, 2, 3, 4, 5]


@login_required   
def flux(request):
    # On sélectionne l'utilisateur et les personnes suivies
    user = get_user(request)
    user_followeds = [pair.followed_user for pair in UserFollows.objects.filter(user=user)]
    user_posts = []
    user_posts.extend(user_followeds)
    user_posts.append(user)
    list_elemts = []
    # On recherche les tickets et reviews souhaitées
    tickets = Ticket.objects.all()
    reviews = Review.objects.all()
    for user_post in user_posts:
        ticket_posts = Ticket.objects.filter(user=user_post)
        review_posts = Review.objects.filter(user=user_post)
        for review in review_posts:
            list_elemts.append(review)
        for ticket in ticket_posts:
            list_elemts.append(ticket)
    # On recherche les reviews des non abonnés
    user_tickets = Ticket.objects.filter(user=user)
    for ticket in user_tickets:
        review_user_tickets = Review.objects.filter(ticket=ticket)
        for review in review_user_tickets:
            if review not in list_elemts:
                list_elemts.append(review)
    # On tri par ordre chronologique
    sorted_list = sorted(list_elemts,
                         key=lambda x: x.time_created,
                         reverse=True)
    # On recherche les reviews de l'utilisateur
    user_review = Review.objects.filter(user=user)
    # On créé une liste de tickets déjà critiqué par l'utilisateur
    tickets_stop_btn = [review.ticket for review in user_review]
    context = {
        'list_elemts': sorted_list,
        'tickets_stop_btn': tickets_stop_btn,
        'tickets': tickets,
        'reviews': reviews,
        'user_followeds': user_posts,
        'stars': STARS
    }
    return render(request, 'book_review/flux.html', context)


@login_required
def posts(request):
    list_elemts = []
    actual_user = get_user(request)
    tickets = Ticket.objects.filter(user=actual_user)
    reviews = Review.objects.filter(user=actual_user)
    for review in reviews:
        list_elemts.append(review)
    for ticket in tickets:
        list_elemts.append(ticket)
    # Cas où l'utilisateur appuis sur le bouton supprimer pour un ticket
    if 'ticket_delete' in request.POST:
        id_to_delete = request.POST.get('ticket_delete')
        ticket_to_delete = Ticket.objects.get(id=id_to_delete)
        if ticket.image and os.path.exists(ticket_to_delete.image.path):
            os.remove(ticket_to_delete.image.path)
        ticket_to_delete.delete()
        return redirect('book_review:posts')
    # Cas où l'utilisateur appuis sur le bouton supprimer pour une review
    if 'review_delete' in request.POST:
        id_to_delete = request.POST.get('review_delete')
        review_to_delete = Review.objects.get(id=id_to_delete)
        review_to_delete.delete()
        return redirect('book_review:posts')
    context = {
        'list_elemts': sorted(list_elemts,
                              key=lambda x: x.time_created,
                              reverse=True),
        'tickets': tickets,
        'reviews': reviews,
        'stars': STARS
    }
    return render(request, 'book_review/posts.html', context)


@login_required
def abonnements(request):
    user = get_user(request)
    message = ''
    if request.method == "POST":
        # Cas où l'utilisateur souhaite suivre quelqu'un
        if 'sub' in request.POST:
            name = request.POST.get('name')
            if name in [user.username for user in User.objects.all()] \
                    and name != user.username \
                    and name not in [pair.followed_user.username for pair in UserFollows.objects.filter(user=user)]:
                pair = UserFollows(
                    user=user,
                    followed_user=User.objects.get(username=name)
                )
                pair.full_clean()
                pair.save()
            else:
                message = "Le nom rentré n'a pas été trouvé, veuillez recommencer."
        # Cas où l'utilisateur souhaite arrêter de suivre une personne
        elif 'unsub' in request.POST:
            unsub_name = request.POST.get('unsub')
            unsub_user = User.objects.get(username=unsub_name)
            unsub_pair = UserFollows.objects.get(user=user,
                                                 followed_user=unsub_user)
            unsub_pair.delete()
    followed_users = UserFollows.objects.filter(user=user)
    followed_bys = UserFollows.objects.filter(followed_user=user)
    context = {
        "followed_users": followed_users,
        "followed_bys": followed_bys,
        "user": user,
        'message': message
    }

    return render(request, 'book_review/abonnements.html', context)


@login_required
def crea_ticket(request, ticket_id=""):
    context = {
    }
    if ticket_id:
        ticket = Ticket.objects.get(id=ticket_id)
        context["ticket"] = ticket
    if request.method == "POST":
        title = request.POST.get('title')
        description = request.POST.get('description')
        user = get_user(request)
        image = request.FILES.get("image")
        # Cas où l'on va modifier un ticket existant
        if ticket_id:
            ticket = Ticket.objects.get(id=ticket_id)
            ticket.title = title
            ticket.description = description
            if image:
                if ticket.image:
                    ticket.image.close()
                    os.remove(ticket.image.path)
                ticket.image = image
        # Cas où l'on créé un nouveau ticket
        else:
            ticket = Ticket(
                title=title,
                description=description,
                user=user,
                image=image
            )
        ticket.full_clean()
        ticket.save()
        return flux(request)
    return render(request, 'book_review/crea_ticket.html', context)


@login_required   
def crea_review(request):
    context = {
    }
    if request.method == "POST":
        title = request.POST.get('title')
        description = request.POST.get('description')
        user = get_user(request)
        image = request.FILES.get('image')
        ticket = Ticket(
            title=title,
            description=description,
            user=user,
            image=image
        )
        ticket.full_clean()
        ticket.save()
        rating = request.POST.get('rating')
        headline = request.POST.get('headline')
        body = request.POST.get('body')
        review = Review(
            rating=rating,
            headline=headline,
            body=body,
            user=user,
            ticket=ticket
        )
        review.full_clean()
        review.save()
        return flux(request)
    return render(request, 'book_review/crea_review.html', context)


@login_required   
def reply_ticket(request, ticket_id):
    ticket = Ticket.objects.filter(id=ticket_id)[0]
    context = {
        'ticket': ticket
    }
    user = get_user(request)
    test_review = Review.objects.filter(ticket=ticket, user=user)
    if test_review:
        context['actual_review'] = test_review[0]
    if request.method == "POST":
        user = get_user(request)
        rating = request.POST.get('rating')
        headline = request.POST.get('headline')
        body = request.POST.get('body')
        # Cas de modification de review
        if test_review:
            test_review[0].rating = rating
            test_review[0].headline = headline
            test_review[0].body = body
            test_review[0].full_clean()
            test_review[0].save()
        # Cas de création de review
        else:
            review = Review(
                rating=rating,
                headline=headline,
                body=body,
                user=user,
                ticket=ticket
            )
            review.full_clean()
            review.save()
        return flux(request)

    return render(request, 'book_review/reply_ticket.html', context)

LITReview/book_review/templates/book_review/abonnements.html
{% extends "base.html" %}

{% block content %}
<section>
<form class="form-inline container" method="post" action="{% url 'book_review:abonnements' %}">
    {% csrf_token %}
    <div class="row justify-content-center">
        <div class="col text-center">
            <div class="row justify-content-center">
                <h2 class="sub-title">Suivre d'autres utilisateurs</h2>
                <div class="error-id mb-3">{{message}}</div>
                <div class="col-8">
                    <label for="usertofollow" class="visually-hidden">Nom d'utilisateur</label>
                    <input type="text" class="form-control" id="usertofollow" placeholder="Nom d'utilisateur" name="name">
                </div>
                <div class="col-1">
                    <button type="submit" name="sub" class="btn btn-primary mb-3">Envoyer</button>
                </div>
            </div>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col text-center">
            <h2 class="sub-title">Abonnements</h2>
            {% for followed_user in followed_users %}
            <div class="input-group">
                <input type="text" class="form-control" value="{{followed_user.followed_user.username}}" aria-label="Nom personnage" readonly>
                <button class="btn btn-outline-secondary" value="{{followed_user.followed_user.username}}" name="unsub" type="submit">Désabonner</button>
            </div>
            {% endfor %}
            {{unsub_user}}
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col text-center">
            <h2 class="sub-title">Abonnés</h2>
            {% for followed_by in followed_bys %}
            <input class="form-control" type="text" value="{{followed_by.user.username}}" aria-label="Nom Personnage" readonly>
            {% endfor %}
        </div>
    </div>
</form>
</section>
{% endblock %}

LITReview/book_review/templates/book_review/crea_review.html
{% extends "base.html" %}

{% block content %}
<section>
<h2 class="text-center mt-3">Créer une critique</h2>
<form class="form-inline container" method="post" action="{% url 'book_review:crea_review' %}" enctype="multipart/form-data">
    {% include 'book_review/ticket.html' with stop_btn=1 %}
    <hr class="sep">
    {% include 'book_review/review.html'%}
</form>
</section>
{% endblock %}

LITReview/book_review/templates/book_review/crea_ticket.html
{% extends "base.html" %}

{% block content %}
<section class="container">
    {% if ticket %}
    <h2 class="align-self-center">Modification du ticket</h2>
    {% else %}
    <h2 class="align-self-center">Créer un ticket</h2>
    {% endif %}
        {% if ticket %}
        <form class="form-inline" method="post" action="{% url 'book_review:crea_ticket' ticket.id %}" enctype="multipart/form-data">
        {% else %}
        <form class="form-inline" method="post" action="{% url 'book_review:crea_ticket' %}" enctype="multipart/form-data">
        {% endif %}
        {% include 'book_review/ticket.html' %}
        </form>
</section>
{% endblock %}

LITReview/book_review/templates/book_review/display_review.html
<div class="container post-display">
    <div class="row justify-content-between">
        <p class="col-auto">{{review.user.username}} a publié une critique</p>
        <p class="col-auto">{{review.time_created}}</p>
    </div>
    <div class="post-text">{{review.headline}} - Note : {{review.rating}}&emsp;   
    {% for i in stars %}
    {% if i <= review.rating %}
        <i class="rating rating-or">☆</i>
    {% else %}
        <i class="rating rating-bl">☆</i>
    {% endif %}
    {% endfor %}
    </div>
    <p class="post-text">{{review.body}}</p>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-6 review-bg">
                <p>Ticket - {{review.ticket.user.username}}</p>
                <p class="post-text">{{review.ticket.title}}</p>
                {% if review.ticket.image %}
                <div class="row justify-content-center">
                    <img src="{{review.ticket.image.url}}"  class="img_post"/>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
    {% if post %}
    <form class="form-inline" method="post" action="{% url 'book_review:posts' %}">
    {% csrf_token %}
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <a href="{% url 'book_review:reply_ticket' review.ticket.id %}" class="col-auto btn btn-primary mx-3" role="button">Modifier</a>
        <button class="col-auto btn btn-primary" role="button" type="submit" name="review_delete" value="{{review.id}}">Supprimer</button>
    </div>
    {% endif %}
    </form>
</div>

LITReview/book_review/templates/book_review/display_ticket.html
<div class="container post-display">
    <div class="row justify-content-between">
        <p class="col-auto">{{ticket.user.username}} a demandé une critique</p>
        <p class="col-auto">{{ticket.time_created}}</p>
    </div>    
        <p class="post-text">Titre : {{ticket.title}}</p>
        <p class="post-text">{{ticket.description}}</p>
        {% if ticket.image %}
        <div class="row justify-content-center">
            <img src="{{ticket.image.url}}"  class="img_post"/>
        </div>
        {% endif %}
        {% if not stop_btn %}
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <a href="{% url 'book_review:reply_ticket' ticket.id %}" class="col-auto btn btn-primary" role="button">Créer une critique</a>
        </div>
        {% endif %}
        {% if post %}
        <form class="form-inline" method="post" action="{% url 'book_review:posts' %}">
        {% csrf_token %}
        <div class="d-grid gap-2 d-md-flex justify-content-md-end mt-3">
            <a href="{% url 'book_review:crea_ticket' ticket.id %}" class="col-auto btn btn-primary mx-3" role="button">Modifier</a>
            <button class="col-auto btn btn-primary" role="button" type="submit" name="ticket_delete" value="{{ticket.id}}">Supprimer</button>
        </div>
        </form>
        {% endif %}        
</div>

LITReview/book_review/templates/book_review/flux.html
{% extends "base.html" %}
{% block content %}
<section>
<div class="container button-create">
    <div class="row justify-content-center">
        <a href="{% url 'book_review:crea_ticket' %}" class="col-auto btn btn-dark" role="button">Demander une critique</a>
        <a href="{% url 'book_review:crea_review' %}" class="col-auto offset-1 btn btn-dark" role="button">Créer une critique</a>
    </div>
</div>
{% for elemt in list_elemts %}
{% if elemt in tickets %}
    {% if elemt in tickets_stop_btn %}
    {% include 'book_review/display_ticket.html' with ticket=elemt stop_btn=1 %}
    <hr class="sep">
    {% else %}
    {% include 'book_review/display_ticket.html' with ticket=elemt %}
    <hr class="sep">
    {% endif %}
{% elif elemt in reviews %}
    {% include 'book_review/display_review.html' with review=elemt %}
    <hr class="sep">
{% endif %}
{% empty %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-auto">
            <h2 class="txt-no-post">Désolé aucune donnée sur le flux !</h2>
        </div>
    </div>
</div>
</section>
{% endfor %}
{% endblock %}

LITReview/book_review/templates/book_review/posts.html
{% extends "base.html" %}

{% block content %}
{% for elemt in list_elemts %}
{% if elemt in tickets %}
    {% include 'book_review/display_ticket.html' with ticket=elemt stop_btn=1 post=1 %}
    <hr class="sep">

{% elif elemt in reviews %}
    {% if elemt.ticket %}
    {% include 'book_review/display_review.html' with review=elemt post=1 %}
    <hr class="sep">
    {% endif %}
{% endif %}
{% empty %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-auto">
            <h2 class="txt-no-post">Désolé aucune activité pour le moment !</h2>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

LITReview/book_review/templates/book_review/reply_ticket.html
{% extends "base.html" %}

{% block content %}
{% if actual_review %}
<h2 class="text-center mt-3">Modifier votre critique</h2>
{% else %}
<h2 class="text-center mt-3">Créer une critique</h2>
{% endif %}
<section class="container">
    <p>Vous êtes en train de poster en réponse à :</p>
    {% include 'book_review/display_ticket.html' with stop_btn=1 ticket=ticket %}
    <hr class="sep">
    <form class="form-inline" method="post" action="{% url 'book_review:reply_ticket' ticket.id %}">
    {% include 'book_review/review.html' %}
    </form>
</section>
{% endblock %}

LITReview/book_review/templates/book_review/review.html
{% csrf_token %}

<p>Critique</p>
<div class="row justify-content-center">
    <div class="col mt-3">
        <p>Titre</p>
        <input class="form-control" type="text" name="headline" maxlength="128" value="{{actual_review.headline}}" required>
    </div>
</div>
<div class="row justify-content-center">
    <div class="col mt-3">
        <p>Note</p>
        <div class="row justify-content-center">
            <div class="col-1 form-check">
                <input class="form-check-input" type="radio" name="rating" id="rating1" value="0" {% if actual_review.rating == 0 %}checked{% endif %} required>
                <label class="form-check-label" for="rating1">
                0
                </label>
            </div>
            <div class="col-1 form-check">
                <input class="form-check-input" type="radio" name="rating" id="rating2" value="1" {% if actual_review.rating == 1 %}checked{% endif %}>
                <label class="form-check-label" for="rating2">
                1
                </label>
            </div>
            <div class="col-1 form-check">
                <input class="form-check-input" type="radio" name="rating" id="rating3" value="2" {% if actual_review.rating == 2 %}checked{% endif %}>
                <label class="form-check-label" for="rating3">
                2
                </label>
            </div>
            <div class="col-1 form-check">
                <input class="form-check-input" type="radio" name="rating" id="rating4" value="3" {% if actual_review.rating == 3 %}checked{% endif %}>
                <label class="form-check-label" for="rating4">
                3
                </label>
            </div>
            <div class="col-1 form-check">
                <input class="form-check-input" type="radio" name="rating" id="rating5" value="4" {% if actual_review.rating == 4 %}checked{% endif %}>
                <label class="form-check-label" for="rating5">
                4
                </label>
            </div>
            <div class="col-1 form-check">
                <input class="form-check-input" type="radio" name="rating" id="rating6" value="5" {% if actual_review.rating == 5 %}checked{% endif %}>
                <label class="form-check-label" for="rating6">
                5
                </label>
            </div>
        </div>
    </div>
</div>
<div class="row justify-content-center">
    <div class="col mt-3">
        <p>Commentaire</p>
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="5" maxlength="8192" name="body" required>{{actual_review.body}}</textarea>
    </div>
</div>
{% if not stop_btn %}
<div class="d-grid justify-content-end">
    <input class="btn btn-primary mt-3" type="submit" value="Envoyer">
</div>
{% endif %}

LITReview/book_review/templates/book_review/ticket.html
{% csrf_token %}

{% if stop_btn %}
<p>Livre/Article</p>
{% endif %}
<div class="form-group row-auto justify-content-center">
    <div class="col mt-3">
        <p>Titre</p> 
        <input class="form-control" type="text" name="title" maxlength="128" value="{{ticket.title}}" required>
    </div>
</div>
<div class="form-group row-auto justify-content-center">
    <div class="col mt-3">
        <p>Description</p>
        <textarea class="form-control" id="description" name="description" maxlength="2048" rows="9" required>{{ticket.description}}</textarea>
    </div>
</div>
<div class="form-group row-auto justify-content-center mt-3">
    <p>Image</p>
    {% if ticket.image %}
        <img src="{{ticket.image.url}}"  class="img-ticket img_post mt-0 mb-3"/>
    {% endif %}
    <img src="#"  class="img-preview img_post mt-0 mb-3"/>
    <div class="col ">
        <input class="custom-file-input" type="file" name="image" accept="image/*" >
    </div>
</div>
{% if not stop_btn %}
<div class="d-grid justify-content-end">
    <input class="btn btn-primary mt-3" type="submit" value="Envoyer">
</div>
{% endif %}
{% load static %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="{% static 'book_review/js/preview_image.js' %}"></script>